### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by hdwhdwhdw** [Dev-On-Play/spring-project#3]
# 추천 주제
1. 슬랙 무료버전 히스토리 UI 구현
2. 공간 소개 및 대여 플랫폼
3. 온라인 모각코 및 스터디 출석 체크, 일정 관리, 자료 관리 서비스
4. 독서 기록 및 공유, 추천 시스템
5. 스터디그룹 관리 플랫폼

----

## 개인 별로 주제를 선정 후 아래 리스트를 작성해주세요.
- 주제 선정 이유
- 구현에 사용할 / 사용하고 싶은 언어 및 툴
- 필수적으로 구현할 기능
- 선택적으로 구현할 기능 
- 사용빈도(MAU)

**Comment by hdwhdwhdw** [comment]
독서 기록 및 공유, 추천 시스템

**Comment by hdwhdwhdw** [comment]
슬랙 무료버전 히스토리 UI 구현

- 주제 선정 이유 : 슬랙 무료 버전을 사용 했을때, 90일이 지난 대화는 보지 못하는게 아쉬움, 스페이스마스터?면 json 파일로 내려 받을 수 있기에 이를 디비에 저장하거나, html 로 파싱해서 보여주면 검색하기 쉬울듯
- 구현에 사용할 / 사용하고 싶은 언어 및 툴 : java + spring+boot + mybatis + thymeleaf + oracle(mariadb)
- 필수적으로 구현할 기능 : json 파일을 업로드하여, 자체 디비에 마이그레이션 또는 html 에 뿌리는 기능
- 선택적으로 구현할 기능 : 설정 기간별로 자동으로 json 파일을 다운받아서, 주기적으로 디비화
- 사용빈도(MAU) : 90일이 지난 스페이스가 있거나 과거 기록이 궁금할때, 사용할 것 같음

**Comment by jundoopop** [comment]
### 스터디 그룹 관리 플랫폼

#### 주제 선정 이유
- 개인이든 단체든 참여하는 스터디에 특화한 플랫폼으로 더 효율적인 공부 시간 관리를 해보고 싶어서?
- 노션에서 템플릿을 만드는 수고를 덜어주고 싶어서

#### 구현에 사용할 / 사용하고 싶은 언어 및 툴
- Spring Boot, JPA / Docker, 

#### 필수적으로 구현할 기능
- 출석 관리
- 회의록 아카이브
- 달력, 일정 확인
- 로그인 + 소셜 로그인
- 출석률 표시
- 스터디그룹 공동 tasks
- 회원 개인 tasks
- 스터디장의 강퇴 권한

#### 선택적으로 구현할 기능
- 지금까지 참여한 스터디 목록: 해당 회원이 어떤 분야를 공부했는지 모두가 확인 가능
- 회원 평가: 당근 온도처럼 스터디원 평판 표시

#### 사용빈도(MAU)
- 커뮤니티 회원들, 그리고 학생들 대상

**Comment by eunguin** [comment]
슬랙 무료버전 히스토리 UI 구현 및 스터디 그룹 관리 플랫폼
주제 선정 이유
기존 슬랙, 노션과 같은 협업툴 프로그램에서
지난 대화나 아님 단점을 보안하여
더 편리한 플랫폼을 개발해서 사용해보고 싶습니다:)
구현에 사용할 / 사용하고 싶은 언어 및 툴
Java spring(혹은 spring boot),mybatis, react, docker, aws(oracle db)
필수적으로 구현할 기능
메신저(지난 대화보기 가능 및 다운로드)
달력,할일, 여러 항목,일정,출석체크 기록 및 통계보이기
개인 페이지,그룹 페이지 여러기능
(특정기준에 따라 잠금 페이지 기능 및 다운, 작성할때 누가 작성하는지 보이게 하는기능)
로그인,소셜로그인
마이페이지(접속 온라인 기능, 개인 로그인 설정, 알림 설정)
선택적으로 구현할 기능
플랫폼 모바일 버전도 가능하면 해봤으면 좋겠습니다:)
노션과 슬랙이 합쳐진 플랫폼을 더 보안한다면 
체계적 정리 도움말 및 사용법에 관련된 챗봇 기능도 넣어봤으면 좋겠습니다.. 욕심임댜..
사용빈도(MAU)
커뮤니티, 협업 사용자, 필요한 모든사람!

**Comment by soobnini** [comment]
온라인 모각코 및 스터디 출석 체크, 일정 관리, 자료 관리 서비스

주제 선정 이유: 가장 실 사용자 입장에서 생각해볼수있는 프로젝트

구현에 사용할 / 사용하고 싶은 언어 및 툴

> 타임리프  or jstl +  Java / Spring + JPA + Mariadb

필수 구현기능: 

> 회원 관리 기능(가입/탈퇴/로그인/출석체크 등)

> 일정 및 task 관리 기능(캘린더 및 일정 등록/투두리스트 등)

선택적으로 구현할 기능

> 메신저 및 피드....?

사용 빈도: 모각코 및 개발스터디 이외에도 다양한 스터디에 활용 가능할 듯 합니다
