### ISSUE TITLE
팀별 프로젝트 기획안 1차

### ISSUE THREAD

**Issue by hdwhdwhdw** [Dev-On-Play/spring-project#4]
> 참고    
> 아래에는 **스터디**와 **모각코**를 동일하게 **스터디**로 통일해서 작성했습니다.    
> 편의를 위해 작성하였고, 이를 구별하여 기획 및 구현 하셔도 됩니다.    
> 모바일 퍼스트 화면의 예시 사이트 : [펫프렌즈](https://m.pet-friends.co.kr/main/tab/2)
> 1차로 ~2/28일까지 제출 후 중간 검토, 2차로 다음 모임 전까지 완성 해주시면 될 것 같습니다.

#### 사용자    
- 로그인(소셜만 사용하는 쪽으로)   
    - 사용자 권한
        - 스터디장(생성, 종료, 강퇴)
        - 스터디원(참여, 취소)
- 마이페이지
    - 접속 상태(온라인/오프라인) 표시
    - 자신의 출석 내역 보기
    - 알림 설정
    
#### 스터디   
- 생성
    - 스터디 분야 설정
    - 날짜, 시간별 일정 등록
    - 스터디에 사용자 참여, 취소
    - 무단 불참 시 해당 사용자에 대한 패널티 설정

- 진행
    - 참석/불참 확인
    - 스터디 참여인원간 소통할 메신저(지난 대화보기 가능 및 다운로드)
    - 일정 및 task 관리
        - 자체 캘린더/투두리스트 또는 외부 연동

- 종료
    - 회고 기록
    - 개인 페이지, 그룹 페이지
    - 사용한 자료 아카이빙

#### 관리자
- 스터디장, 스터디원 관리
    - 가입/탈퇴/로그인/출석체크
- 전체 기록 및 개별 통계
    - 스터디 활성화 정도
- 스터디 차단 기능
    - 불량 스터디 접근 제한

### 선택적으로 구현할 기능
- 지금까지 참여한 스터디 목록 : 해당 회원이 어떤 분야를 공부했는지 모두가 확인
- 사용자 평가 : 당근 온도처럼 스터디장/원 평판 표시
- 사용자 추천 : 시간대/장소/분야가 비슷한 멤버 추천
- 참여 기록 공유 : 깃허브 잔디와 같이
- 노션과 슬랙 등 외부 툴과 연동
- 사용법에 대한 챗봇
- 플랫폼에 대한 정보를 알 수 있는 피드

**Comment by hdwhdwhdw** [comment]
위 내용을 참고하여, 팀별로 기획안을 만들어 주시면 됩니다!

**Comment by MoonJeWoong** [comment]
# 💡 서비스 한마디 정의 : **커뮤니티 내 온라인 모각코 스케쥴러**


# 로그인

- 회원가입
    - 일반 회원 로그인
- 로그인(소셜만 사용하는 쪽으로)
    - 일반 회원 로그인

⇒ 관리자 계정은 따로 관리

# 마이페이지

- 접속 상태(온라인/오프라인) 표시
    - => 굳이 MVP에 있어야 하는 기능인가? 들이는 공수에 비해 사용자들의 경험이 유의미하게 향상되는가?
    - 우리 서비스에서 실시간으로 스터디 진행이 이뤄지는 것은 당장 아니기에 MVP에 포함되기에는 부적절하다고 판단.
- 자신의 출석 내역 보기
    - 자신이 참여했던 스터디 목록
        - 날짜 별 필터링
        - 카테고리 별 필터링 등... (필터링 태그는 더 추가해볼 가능성이 있을 듯)
        - 스터디 이름, 스터디 참여 인원, 종료 여부, 참석 여부
    - 참여 예정인 스터디 목록
        - 스터디 예정일까지 남은 D-Day 표시 기능
        - 스터디 이름, 스터디 참여 인원, 남은 D-Day
- 알림 설정
    - => 사용자에게 무슨 내용을 알림으로 고지할 것인지? 웹 서비스인데 알림 설정을 어떤 방식으로 구현할 것인지?
    - 이메일 알림(비용 절감?), 핸드폰 문자(유료) → 이벤트 하루~이틀 전 알림 전송
    - 캘린더 접근 초대(비용 모름) → 외부 캘린더 연동 API
        - 스터디 참석하면 사용자 계정 캘린더 접근해서 일정 자동 생성 및 알림 설정

# 스터디

- 생성
    - 일반 회원 중에서 스터디 일정을 만든 사람은 해당 일정에 대한 권한 부여
        - 스터디장(생성, 종료, 강퇴)
        - 스터디원(참여, 취소)
    
    - 일단 회원가입을 해서 로그인을 해요. 
    그 다음 누군가는 스터디를 만들고 싶겠죠?
    스터디를 만든 사람 => 해당 스터디에 대한 스터디장
    다른 회원들은 그 스터디에 참여하거나 나갈 수 있 는 느낌.
    
    - 무단 불참 시 해당 사용자에 대한 패널티 설정
        - 스터디를 개설 모집 마감 기한? 실제로 시작하는 날짜? 일정에 대한 기획 논의 필요
        - 모집 마감 기한 이전
            - 참여자가 마음대로 참여 혹은 나가기 가능
        - 모집 마감 기한 이후 ~ 실제 시작일
            - 참여자가 마음대로 참여 혹은 나가기 불가능
            - 나가는 참여자에게 패널티 부여?
                - (기본기능) 일정 시간 이후 취소하면 패널티
                - 세부 정책은 좀 더 구체화 필요
    
    - 스터디 일정 개설
        - 스터디 분야 설정
        - 참여 인원 제한 설정
        - 스터디 개요 및 상세 설명 입력
        - 날짜, 시간별 일정 등록
    
    - 스터디에 사용자 참여, 나가기
        - 세부 정책은 좀 더 구체화 필요
    
    - 기간이 지난 스터디는 자동 종료 처리
        - 스터디 진행 날짜 기준으로 하루가 지나도록 진행 혹은 완료 처리가 안되는 경우? ⇒ 자동 종료 처리한다.
        - 세부 정책은 좀 더 구체화 필요

- 진행
    - 스터디장이 스터디원들의 참석/불참 체크하는 기능 필요
    - 스터디 참여인원 간 소통할 메신저(지난 대화보기 가능 및 다운로드)
        - ⇒  우리 서비스 내에서 스터디 진행 인원들이 서로 채팅할 일이 있을까?
        - 좀 더 아이디어가 구체화될 필요성이 보임.
        - 스터디 일정 자체에서 의견을 나눌 수 있는? 혹은 추가 공지사항?
            - 스터디 페이지 ⇒ 댓글 정도로 의견 나눌 수 있으면 되지 않을까?

- 종료
    - 개인 페이지, 그룹 페이지 (?)
        - 어떤 내용인지 잘 와닿지 않음
    - 사용한 자료 아카이빙
        - 스터디 개설 후 대기 기간에 자료 공유에도 사용될 수 있을 여지가 있음
    
    # 관리자
    
    - 스터디장, 스터디원 관리
        - 가입/탈퇴/로그인/출석체크
    - 전체 기록 및 개별 통계
        - 스터디 활성화 정도
        - ⇒ 어떤 지표에 대한 것을 관리자가 파악하고 싶을지 먼저 생각해봐야 할 부분.
    - 스터디 차단 기능
        - 불량 스터디 접근 제한
        - ⇒ 불량 스터디의 정의는 어떤 방식으로 할 것인지…?
        - 신고 기능이 존재해서 신고된 스터디를 블록 처리 하는건가…?
    - 관리자 회원 로그인
    
    ---
    
    이후 추가를 고려해볼 기능
    
    - 스터디장이 패널티를 먹은 스터디원에 대해 패널티 면제를 할 수 있는 기능
    - 스터디장이 스터디 진행을 하지 않은 경우 어떻게 처리할 지
        - 운영측면의 얘기라서 일단은 보류
    - 일정 및 task 관리
        - 지라 혹은 노션 같은 대시보드 기능
        - 자체 캘린더/투두리스트 또는 외부 연동
        - ⇒  요 기능도 MVP인가에 대해서는 재고가 필요해 보인다.
    - 회고 기록 (사용자에게 실질적으로 와닿는 기능일까?)

**Comment by hdwhdwhdw** [comment]
⇒ 불량 모각코의 정의는 어떤 방식으로 할 것인지
> 신고를 많이 받은 모각코라고 생각합니다

**Comment by rave189** [comment]
모각코장, 모각코 참여인원 관리
가입/탈퇴/로그인/출석체크

-> 관리자에서 로그인과 출석체크가 어떤 기능을 하는지 잘 모르겠습니다.

**Comment by hdwhdwhdw** [comment]
⇒ 어떤 지표에 대한 것을 관리자가 파악하고 싶을지 먼저 생각해봐야 할 부분.
관리자!=모각코 주최자.
많이 와주시는 사용자

**Comment by hdwhdwhdw** [comment]
- 모각코 관리 프로그램

- 로그인(소셜로그인)
    - 다중가입을 방지하기 위해 이메일을 체크한다.
    - 기타 개인정보는 수집하지 않는다.

- 마이페이지
    - 자신 참석했던 모각코 내역을 볼 수 있다.
    - 앞으로 참석 예정인 모각코 일정을 볼 수 있다.
    - 알림 메뉴를 만들어 로그인하면, 나와 관련된 알림을 볼 수 있다.

- 생성
    - 모각코 생성시 이름/모임일/참여인원/최소인원/상세내용 등을 설정할 수 있다.
    - 생성한 사람이 모각코장이 된다.
        - 초기에 생성 가능한 권한을 일부에게만 부여
            - 서비스 안정화 후 모두에게 부여
    - 모각코 분야를 설정할 수 있다.
    - 모임 조건(최소인원 미달성 등)이 모임일까지 달성되지 않을 경우 모임은 취소 된다.

- 참여
    - 모각코 하루 까지는 참여 또는 취소를 자유롭게 할 수 있다.
    - 모각코 당일에는 취소시 패널티를 부여 할 수 있다.(자동 부여)
    - 모각코장이 특정 사용자에 대한 참여/불참을 설정 할 수 있다.
    - 참여와 관련된 질의를 할 수 있는 댓글 기능을 사용할 수 있다.(메신저 대체)
    - 참여한 상호간 모각코의 평점을 매길 수 있다.(신고)
    - 참여한 모각코에 파일첨부를 할 수 있다.
        - 모각코에 사용된 자료(크기 및 확장자 제한)

- 관리자
    - 모각코장/모각코 참여인원 등, 전체 사용자에 대한 관리를 할 수 있다.
    - 전체 모각코에 대한 일정을 파악할 수 있다.
    - 생성된 모각코에 대해 평점을 관리할 수 있다.
